<?php
namespace backend\models;

use Yii;

/**
 * This is the model class for table "case_record".
 *
 * @property string $id
 * @property string $name
 * @property integer $sex
 * @property integer $nation
 * @property integer $age
 * @property string $politics_status
 * @property string $join_party_date
 * @property string $organization_name
 * @property string $duty
 * @property string $rank
 * @property integer $is_monitor
 * @property integer $is_official
 * @property string $clue_code
 * @property string $clue_people_code
 * @property string $clue_accept_time
 * @property string $clue_manage_office
 * @property string $clue_source
 * @property integer $clue_violations_type
 * @property integer $clue_outlawed_type
 * @property integer $clue_disposition_method
 * @property string $clue_summary
 * @property string $clue_protokaryon_report
 * @property string $case_code
 * @property string $case_people_code
 * @property string $case_register_time
 * @property string $case_register_office
 * @property string $case_summary
 * @property string $case_register_report
 * @property string $case_register_decision
 * @property string $case_review_report
 * @property string $settle_accept_time
 * @property string $settle_accept_report
 * @property string $settle_conclude_time
 * @property string $settle_finish_time
 * @property string $settle_party_disposal
 * @property string $settle_political_disposal
 * @property string $settle_disposal_decision
 * @property string $settle_judiciary_time
 * @property string $settle_prosecutor_time
 * @property string $settle_prosecutor_details
 * @property integer $del_status
 * @property string $create_date
 * @property string $update_time
 */
class CaseRecord extends \backend\models\BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'case_record';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sex', 'nation', 'age', 'is_monitor', 'is_official', 'clue_violations_type', 'clue_outlawed_type', 'clue_disposition_method', 'del_status'], 'integer'],
            [['join_party_date', 'clue_accept_time', 'case_register_time', 'settle_accept_time', 'settle_conclude_time', 'settle_finish_time', 'settle_judiciary_time', 'settle_prosecutor_time', 'create_date', 'update_time'], 'safe'],
            [['name', 'politics_status', 'organization_name', 'duty', 'rank', 'clue_code', 'clue_people_code', 'clue_manage_office', 'clue_source', 'case_code', 'case_people_code', 'case_register_office'], 'string', 'max' => 25],
            [['clue_summary', 'clue_protokaryon_report', 'case_summary', 'case_register_report', 'case_register_decision', 'case_review_report', 'settle_accept_report', 'settle_party_disposal', 'settle_political_disposal', 'settle_disposal_decision', 'settle_prosecutor_details'], 'string', 'max' => 225]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '姓名',
            'sex' => '性别',
            'nation' => '民族',
            'age' => '年龄',
            'politics_status' => '政治面貌',
            'join_party_date' => '入党时间',
            'organization_name' => '单位',
            'duty' => '职务',
            'rank' => '职级',
            'is_monitor' => '是否监察对象',
            'is_official' => '是否公务员',
            'clue_code' => '线索编码',
            'clue_people_code' => '线索人员编码',
            'clue_accept_time' => '受理时间',
            'clue_manage_office' => '办理机关',
            'clue_source' => '线索来源',
            'clue_violations_type' => '违纪类型',
            'clue_outlawed_type' => '违法类型',
            'clue_disposition_method' => '处置方式',
            'clue_summary' => '线索摘要',
            'clue_protokaryon_report' => '初核报告',
            'case_code' => '案件编码',
            'case_people_code' => '案件人员编码',
            'case_register_time' => '立案时间',
            'case_register_office' => '立案机关',
            'case_summary' => '简要案情',
            'case_register_report' => '立案报告',
            'case_register_decision' => '立案决定书',
            'case_review_report' => '审查报告',
            'settle_accept_time' => '审理受理时间',
            'settle_accept_report' => '审理报告',
            'settle_conclude_time' => '审结时间',
            'settle_finish_time' => '结案时间',
            'settle_party_disposal' => '党纪处分',
            'settle_political_disposal' => '政纪处分',
            'settle_disposal_decision' => '处分决定',
            'settle_judiciary_time' => '移送司法时间',
            'settle_prosecutor_time' => '公检法受理时间',
            'settle_prosecutor_details' => '公检法处理内容',
            'del_status' => '删除状态',
            'create_date' => '创建时间',
            'update_time' => '更新时间',
        ];
    }

  /**
     * 返回数据库字段信息，仅在生成CRUD时使用，如不需要生成CRUD，请注释或删除该getTableColumnInfo()代码
     * COLUMN_COMMENT可用key如下:
     * label - 显示的label
     * inputType 控件类型, 暂时只支持text,hidden  // select,checkbox,radio,file,password,
     * isEdit   是否允许编辑，如果允许编辑将在添加和修改时输入
     * isSearch 是否允许搜索
     * isDisplay 是否在列表中显示
     * isOrder 是否排序
     * udc - udc code，inputtype为select,checkbox,radio三个值时用到。
     * 特别字段：
     * id：主键。必须含有主键，统一都是id
     * create_date: 创建时间。生成的代码自动赋值
     * update_date: 修改时间。生成的代码自动赋值
     */
    public function getTableColumnInfo(){
        return array(
        'id' => array(
                        'name' => 'id',
                        'allowNull' => false,
//                         'autoIncrement' => true,
//                         'comment' => 'ID',
//                         'dbType' => "mediumint(8) unsigned",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => true,
                        'phpType' => 'string',
                        'precision' => '8',
                        'scale' => '',
                        'size' => '8',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('id'),
                        'inputType' => 'hidden',
                        'isEdit' => true,
                        'isSearch' => true,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'name' => array(
                        'name' => 'name',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '姓名',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('name'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'sex' => array(
                        'name' => 'sex',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '性别',
//                         'dbType' => "int(2)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '2',
                        'scale' => '',
                        'size' => '2',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('sex'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'nation' => array(
                        'name' => 'nation',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '民族',
//                         'dbType' => "int(2)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '2',
                        'scale' => '',
                        'size' => '2',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('nation'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'age' => array(
                        'name' => 'age',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '年龄',
//                         'dbType' => "int(2)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '2',
                        'scale' => '',
                        'size' => '2',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('age'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'politics_status' => array(
                        'name' => 'politics_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '政治面貌',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('politics_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'join_party_date' => array(
                        'name' => 'join_party_date',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '入党时间',
//                         'dbType' => "date",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'date',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('join_party_date'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'organization_name' => array(
                        'name' => 'organization_name',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '单位',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('organization_name'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'duty' => array(
                        'name' => 'duty',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '职务',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('duty'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'rank' => array(
                        'name' => 'rank',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '职级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('rank'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'is_monitor' => array(
                        'name' => 'is_monitor',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '是否监察对象',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('is_monitor'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'is_official' => array(
                        'name' => 'is_official',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '是否公务员',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('is_official'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_code' => array(
                        'name' => 'clue_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '线索编码',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_people_code' => array(
                        'name' => 'clue_people_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '线索人员编码',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_people_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_accept_time' => array(
                        'name' => 'clue_accept_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '受理时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_accept_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_manage_office' => array(
                        'name' => 'clue_manage_office',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '办理机关',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_manage_office'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_source' => array(
                        'name' => 'clue_source',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '线索来源',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_source'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_violations_type' => array(
                        'name' => 'clue_violations_type',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '违纪类型',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_violations_type'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_outlawed_type' => array(
                        'name' => 'clue_outlawed_type',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '违法类型',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_outlawed_type'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_disposition_method' => array(
                        'name' => 'clue_disposition_method',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_disposition_method'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_summary' => array(
                        'name' => 'clue_summary',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '线索摘要',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_summary'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_protokaryon_report' => array(
                        'name' => 'clue_protokaryon_report',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '初核报告',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_protokaryon_report'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'case_code' => array(
                        'name' => 'case_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '案件编码',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('case_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'case_people_code' => array(
                        'name' => 'case_people_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '案件人员编码',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('case_people_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'case_register_time' => array(
                        'name' => 'case_register_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '立案时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('case_register_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'case_register_office' => array(
                        'name' => 'case_register_office',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '立案机关',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('case_register_office'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'case_summary' => array(
                        'name' => 'case_summary',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '简要案情',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('case_summary'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'case_register_report' => array(
                        'name' => 'case_register_report',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '立案报告',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('case_register_report'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'case_register_decision' => array(
                        'name' => 'case_register_decision',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '立案决定书',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('case_register_decision'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'case_review_report' => array(
                        'name' => 'case_review_report',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '审查报告',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('case_review_report'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_accept_time' => array(
                        'name' => 'settle_accept_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '审理受理时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_accept_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_accept_report' => array(
                        'name' => 'settle_accept_report',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '审理报告',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_accept_report'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_conclude_time' => array(
                        'name' => 'settle_conclude_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '审结时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_conclude_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_finish_time' => array(
                        'name' => 'settle_finish_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '结案时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_finish_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_party_disposal' => array(
                        'name' => 'settle_party_disposal',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '党纪处分',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_party_disposal'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_political_disposal' => array(
                        'name' => 'settle_political_disposal',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '政纪处分',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_political_disposal'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_disposal_decision' => array(
                        'name' => 'settle_disposal_decision',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处分决定',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_disposal_decision'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_judiciary_time' => array(
                        'name' => 'settle_judiciary_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '移送司法时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_judiciary_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_prosecutor_time' => array(
                        'name' => 'settle_prosecutor_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '公检法受理时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_prosecutor_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'settle_prosecutor_details' => array(
                        'name' => 'settle_prosecutor_details',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '公检法处理内容',
//                         'dbType' => "varchar(225)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '225',
                        'scale' => '',
                        'size' => '225',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('settle_prosecutor_details'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'del_status' => array(
                        'name' => 'del_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '删除状态',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('del_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'create_date' => array(
                        'name' => 'create_date',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '创建时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('create_date'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'update_time' => array(
                        'name' => 'update_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '更新时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('update_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		        );
        
    }
 
}
